Reply-to: advisor@andrew.cmu.edu
To: %USER%
From: advisor@andrew.cmu.edu
Date: %DATE%
Subject: Required system updates.

%WARNING%

On %CUTOVER%, computers that are registered in the phased out subnet for %BUILDING% will be automatically moved to the new subnet for this building.  After this date, machines not configured for DHCP will not pick up the new IP address information and will no longer work on the Andrew network.

For %BUILDING%, the following machines are registered to your department in the Andrew Network Registration system.  As part of the Network Re-IP project, the network subnet in this building is being changed.  The computers listed below are registered in the old subnet.  As the administrator for these machines, you should change them to the correct subnet by %CUTOVER%.  If you do not make these modifications, registrations for these machines will automatically be updated on %CUTOVER% to the new subnet.  You are encouraged to make this change as soon as possible.  If you have any questions about these instructions please refer to http://www.cmu.edu/computing/dhcp/ or phone the Computing Services Help Center at 268-HELP.


Changing your computer's subnet via the Andrew Network Registration System:

1) Using either Netscape Navigator or Microsoft Internet Explorer go to the URL for each of the computers listed below. 
2) Under the Subnet category, locate the current subnet for your computer. Click Change next to the current subnet name. 
3) In the Building category on the Changing Subnet page, select the name of your building from the drop-down menu. 
4) Click Continue.
5) Select a subnet that is not marked as phase-out
6) Click Continue.
7) Verify the hostname for your computer, then click Update Machine.


NOTE:  Your computer must be configured to use DHCP.  Please verify that your computer is configured to use DHCP. (Instructions can be found at http://www.cmu.edu/computing/dhcp/configure.html)

%INFO%



