Reply-to: advisor@andrew.cmu.edu
To: %USER%
From: advisor@andrew.cmu.edu
Date: %DATE%
Subject: Required system updates.

On %CUTOVER%, Computers that are registered in the subnet %SUBNET% will be automatically updated to a new subnet.  After this date, if your computer is not configured for DHCP, it will not automatically pick up its new IP address. This will cause it to stop working on the Andrew Network.

On subnet %SUBNET%, the Network Group has the following computer(s) registered under your username.  This network subnet is being changed.  The computers listed below are registered in the old subnet.  You should follow these instructions to change your network registration before %CUTOVER%.  If you do not make this change, registrations for these machines will automatically be updated on %CUTOVER% to the new subnet.  

You are encouraged to make this change as soon as possible.  If you have any questions about these instructions please refer to http://www.cmu.edu/computing/dhcp/ or phone the Computing Services Help Center at 268-HELP.


Changing your computer's subnet via the Andrew Network Registration System:

1) Using either Netscape Navigator or Microsoft Internet Explorer go to the URL for each of the computers listed below.
2) Under the Subnet category, locate the current subnet for your computer. Click Change next to the current subnet name.
3) In the Building category on the Changing Subnet page, select the name of your building from the drop-down menu.
4) Click Continue.
5) Select a subnet that is not marked as phase-out
6) Click Continue.
7) Verify the hostname for your computer, then click Update Machine.

NOTE:  Your computer must be configured to use DHCP.  Please verify that your computer is configured to use DHCP. (Instructions can be found at http://www.cmu.edu/computing/dhcp/configure.html)

%INFO%



