\copy _locks from ./netmon-clean/_locks.txt
\copy _sys_info from ./netmon-clean/_sys_info.txt
\copy arp_archive from ./netmon-clean/arp_archive.txt
\copy arp_capture from ./netmon-clean/arp_capture.txt
\copy arp_capture_extra from ./netmon-clean/arp_capture_extra.txt
\copy arp_lastseen from ./netmon-clean/arp_lastseen.txt
\copy arp_map from ./netmon-clean/arp_map.txt
\copy arp_tracking from ./netmon-clean/arp_tracking.txt
\copy arp_tracking_archive from ./netmon-clean/arp_tracking_archive.txt
\copy cam_archive from ./netmon-clean/cam_archive.txt
\copy cam_capture from ./netmon-clean/cam_capture.txt
\copy cam_capture_extra from ./netmon-clean/cam_capture_extra.txt
\copy cam_lastseen from ./netmon-clean/cam_lastseen.txt
\copy cam_tracking from ./netmon-clean/cam_tracking.txt
\copy cam_tracking_archive from ./netmon-clean/cam_tracking_archive.txt
\copy capture_timings from ./netmon-clean/capture_timings.txt
\copy device from ./netmon-clean/device.txt
\copy device_capture from ./netmon-clean/device_capture.txt
\copy device_interface from ./netmon-clean/device_interface.txt
\copy device_mac from ./netmon-clean/device_mac.txt
\copy device_port from ./netmon-clean/device_port.txt
\copy device_timings from ./netmon-clean/device_timings.txt
\copy device_timings_default from ./netmon-clean/device_timings_default.txt
\copy device_types from ./netmon-clean/device_types.txt
\copy device_uplink from ./netmon-clean/device_uplink.txt
\copy device_vlan from ./netmon-clean/device_vlan.txt
\copy devmac_archive from ./netmon-clean/devmac_archive.txt
\copy devmac_capture from ./netmon-clean/devmac_capture.txt
\copy devmac_lastseen from ./netmon-clean/devmac_lastseen.txt
\copy devmac_tracking from ./netmon-clean/devmac_tracking.txt
\copy dhcp_fingerprints from ./netmon-clean/dhcp_fingerprints.txt
\copy dhcp_fingerprints_lib from ./netmon-clean/dhcp_fingerprints_lib.txt
\copy dhcp_leases from ./netmon-clean/dhcp_leases.txt
\copy dhcp_leases_archive from ./netmon-clean/dhcp_leases_archive.txt
\copy group_info from ./netmon-clean/group_info.txt
\copy group_timings from ./netmon-clean/group_timings.txt
\copy groups from ./netmon-clean/groups.txt
\copy groups_attrs from ./netmon-clean/groups_attrs.txt
\copy groups_cache from ./netmon-clean/groups_cache.txt
\copy groups_cache_old from ./netmon-clean/groups_cache_old.txt
\copy groups_rules from ./netmon-clean/groups_rules.txt
\copy interface_capture from ./netmon-clean/interface_capture.txt
\copy interface_process from ./netmon-clean/interface_process.txt
\copy landb from ./netmon-clean/landb.txt
\copy mcast_capture from ./netmon-clean/mcast_capture.txt
\copy mcast_capture_dsn from ./netmon-clean/mcast_capture_dsn.txt
\copy membership from ./netmon-clean/membership.txt
\copy mibs from ./netmon-clean/mibs.txt
\copy ports_archive from ./netmon-clean/ports_archive.txt
\copy ports_capture from ./netmon-clean/ports_capture.txt
\copy ports_tracking from ./netmon-clean/ports_tracking.txt
\copy routes_archive from ./netmon-clean/routes_archive.txt
\copy routes_capture from ./netmon-clean/routes_capture.txt
\copy routes_capture_extra from ./netmon-clean/routes_capture_extra.txt
\copy routes_tracking from ./netmon-clean/routes_tracking.txt
\copy stalk_capture from ./netmon-clean/stalk_capture.txt
\copy stalk_tracking from ./netmon-clean/stalk_tracking.txt
\copy stalk_tracking_archive from ./netmon-clean/stalk_tracking_archive.txt
\copy stalker_archive from ./netmon-clean/stalker_archive.txt
\copy stalker_capture from ./netmon-clean/stalker_capture.txt
\copy stalker_capture_extra from ./netmon-clean/stalker_capture_extra.txt
\copy stalker_lastseen from ./netmon-clean/stalker_lastseen.txt
\copy stalker_tracking from ./netmon-clean/stalker_tracking.txt
\copy topology from ./netmon-clean/topology.txt
\copy topology_staging from ./netmon-clean/topology_staging.txt
\copy topology_staging_arp from ./netmon-clean/topology_staging_arp.txt
\copy topology_tree from ./netmon-clean/topology_tree.txt
\copy trap_varbinds_raw from ./netmon-clean/trap_varbinds_raw.txt
\copy traps from ./netmon-clean/traps.txt
\copy "user" from ./netmon-clean/user.txt
\copy wifi_archive from ./netmon-clean/wifi_archive.txt
\copy wifi_capture from ./netmon-clean/wifi_capture.txt
\copy wifi_lastseen from ./netmon-clean/wifi_lastseen.txt
\copy wifi_tracking from ./netmon-clean/wifi_tracking.txt
\copy wl_location from ./netmon-clean/wl_location.txt
\copy ndp_archive from ./netmon-clean/ndp_archive.txt
\copy ndp_capture from ./netmon-clean/ndp_capture.txt
\copy ndp_lastseen from ./netmon-clean/ndp_lastseen.txt
\copy ndp_tracking from ./netmon-clean/ndp_tracking.txt