\copy _sys_changelog from ./netdb-clean/_sys_changelog.txt
\copy _sys_changerec_col from ./netdb-clean/_sys_changerec_col.txt
\copy _sys_changerec_row from ./netdb-clean/_sys_changerec_row.txt
\copy _sys_dberror from ./netdb-clean/_sys_dberror.txt
\copy _sys_errors from ./netdb-clean/_sys_errors.txt
\copy _sys_info from ./netdb-clean/_sys_info.txt
\copy _sys_scheduled from ./netdb-clean/_sys_scheduled.txt
\copy activation_queue from ./netdb-clean/activation_queue.txt
\copy attribute from ./netdb-clean/attribute.txt
\copy attribute_spec from ./netdb-clean/attribute_spec.txt
\copy billing from ./netdb-clean/billing.txt
\copy building from ./netdb-clean/building.txt
\copy cable from ./netdb-clean/cable.txt
\copy credentials from ./netdb-clean/credentials.txt
\copy dhcp_option from ./netdb-clean/dhcp_option.txt
\copy dhcp_option_type from ./netdb-clean/dhcp_option_type.txt
\copy dns_resource from ./netdb-clean/dns_resource.txt
\copy dns_resource_type from ./netdb-clean/dns_resource_type.txt
\copy dns_zone from ./netdb-clean/dns_zone.txt
\copy groups from ./netdb-clean/groups.txt
\copy mac_vendor from ./netdb-clean/mac_vendor.txt
\copy machine from ./netdb-clean/machine.txt
\copy machine_outlet from ./netdb-clean/machine_outlet.txt
\copy memberships from ./netdb-clean/memberships.txt
\copy network from ./netdb-clean/network.txt
\copy outlet from ./netdb-clean/outlet.txt
\copy outlet_subnet_membership from ./netdb-clean/outlet_subnet_membership.txt
\copy outlet_type from ./netdb-clean/outlet_type.txt
\copy outlet_vlan_membership from ./netdb-clean/outlet_vlan_membership.txt
\copy protections from ./netdb-clean/protections.txt
\copy resdrop from ./netdb-clean/resdrop.txt
\copy service from ./netdb-clean/service.txt
\copy service_membership from ./netdb-clean/service_membership.txt
\copy service_type from ./netdb-clean/service_type.txt
\copy srm_share from ./netdb-clean/srm_share.txt
\copy subnet from ./netdb-clean/subnet.txt
\copy subnet_domain from ./netdb-clean/subnet_domain.txt
\copy subnet_presence from ./netdb-clean/subnet_presence.txt
\copy subnet_registration_modes from ./netdb-clean/subnet_registration_modes.txt
\copy subnet_share from ./netdb-clean/subnet_share.txt
\copy trunk_set from ./netdb-clean/trunk_set.txt
\copy trunkset_building_presence from ./netdb-clean/trunkset_building_presence.txt
\copy trunkset_machine_presence from ./netdb-clean/trunkset_machine_presence.txt
\copy trunkset_vlan_presence from ./netdb-clean/trunkset_vlan_presence.txt
\copy "users" from ./netdb-clean/users.txt
\copy vlan from ./netdb-clean/vlan.txt
\copy vlan_subnet_presence from ./netdb-clean/vlan_subnet_presence.txt
