CREATE INDEX "_sys_changelog_user_idx" ON "_sys_changelog" USING btree ("user");
CREATE INDEX "_sys_changelog_name_idx" ON "_sys_changelog" USING btree ("name");
CREATE INDEX "_sys_changelog_time_idx" ON "_sys_changelog" USING btree ("time");
CREATE INDEX "_sys_changerec_col_1_idx" ON "_sys_changerec_col" USING btree ("changerec_row", "name");
CREATE INDEX "_sys_changerec_row_changelog_idx" ON "_sys_changerec_row" USING btree ("changelog");
CREATE INDEX "_sys_changerec_row_1_idx" ON "_sys_changerec_row" USING btree ("tname", "row");
CREATE INDEX "_sys_errors_1_idx" ON "_sys_errors" USING btree ("errcode", "location", "errfields");
CREATE INDEX "activation_queue_name_idx" ON "activation_queue" USING btree ("name");
CREATE INDEX "attribute_owner_tid_idx" ON "attribute" USING btree ("owner_tid");
CREATE INDEX "attribute_spec_idx" ON "attribute" USING btree ("spec");
CREATE INDEX "attribute_spec_type_idx" ON "attribute_spec" USING btree ("type");
CREATE INDEX "cable_label_from_idx" ON "cable" USING btree ("label_from");
CREATE INDEX "cable_label_to_idx" ON "cable" USING btree ("label_to");
CREATE INDEX "cable_1_idx" ON "cable" USING btree ("label_from", "label_to", "id");
CREATE INDEX "credentials_user_idx" ON "credentials" USING btree ("user");
CREATE INDEX "dhcp_option_1_idx" ON "dhcp_option" USING btree ("type", "tid");
CREATE INDEX "dhcp_option_type_number_idx" ON "dhcp_option_type" USING btree ("number");
CREATE INDEX "dns_resource_name_idx" ON "dns_resource" USING btree ("name");
CREATE INDEX "dns_resource_rname_idx" ON "dns_resource" USING btree ("rname");
CREATE INDEX "dns_resource_name_zone_idx" ON "dns_resource" USING btree ("name_zone");
CREATE INDEX "dns_zone_1_idx" ON "dns_zone" USING btree ("id", "name");
CREATE INDEX "mac_vendor_prefix_idx" ON "mac_vendor" USING btree ("prefix");
CREATE INDEX "machine_host_name_idx" ON "machine" USING btree ("host_name");
CREATE INDEX "machine_host_name_zone_idx" ON "machine" USING btree ("host_name_zone");
CREATE INDEX "machine_ip_address_zone_idx" ON "machine" USING btree ("ip_address_zone");
CREATE INDEX "machine_ip_address_subnet_idx" ON "machine" USING btree ("ip_address_subnet");
CREATE INDEX "machine_ip_address_idx" ON "machine" USING btree ("ip_address");
CREATE INDEX "machine_mac_address_idx" ON "machine" USING btree ("mac_address");
CREATE INDEX "machine_1_idx" ON "machine" USING btree ("ip_address_subnet", "mac_address");
CREATE INDEX "machine_outlet_1_idx" ON "machine_outlet" USING btree ("machine", "outlet");
CREATE INDEX "memberships_gid_idx" ON "memberships" USING btree ("gid");
CREATE INDEX "network_subnet_idx" ON "network" USING btree ("subnet");
CREATE INDEX "outlet_1_idx" ON "outlet" USING btree ("device", "port");
CREATE INDEX "outlet_subnet_membership_1_idx" ON "outlet_subnet_membership" USING btree ("outlet", "subnet", "type", "trunk_type");
CREATE INDEX "outlet_vlan_membership_1_idx" ON "outlet_vlan_membership" USING btree ("outlet", "vlan", "type", "trunk_type");
CREATE INDEX "protections_1_idx" ON "protections" USING btree ("identity", "tname", "tid");
CREATE INDEX "protections_tid_idx" ON "protections" USING btree ("tid");
CREATE INDEX "resdrop_1_idx" ON "resdrop" USING btree ("building", "id");
CREATE INDEX "subnet_share_idx" ON "subnet" USING btree ("share");
CREATE INDEX "subnet_domain_subnet_idx" ON "subnet_domain" USING btree ("subnet");
CREATE INDEX "subnet_domain_domain_idx" ON "subnet_domain" USING btree ("domain");
CREATE INDEX "subnet_domain_1_idx" ON "subnet_domain" USING btree ("id", "domain", "subnet");
CREATE INDEX "subnet_presence_subnet_idx" ON "subnet_presence" USING btree ("subnet");
CREATE INDEX "subnet_presence_building_idx" ON "subnet_presence" USING btree ("building");
CREATE INDEX "subnet_registration_modes_1_idx" ON "subnet_registration_modes" USING btree ("subnet", "mode");
CREATE INDEX "trunkset_building_presence_trunk_set_idx" ON "trunkset_building_presence" USING btree ("trunk_set");
CREATE INDEX "trunkset_building_presence_buildings_idx" ON "trunkset_building_presence" USING btree ("buildings");
CREATE INDEX "trunkset_machine_presence_trunk_set_idx" ON "trunkset_machine_presence" USING btree ("trunk_set");
CREATE INDEX "trunkset_machine_presence_device_idx" ON "trunkset_machine_presence" USING btree ("device");
CREATE INDEX "trunkset_vlan_presence_trunk_set_idx" ON "trunkset_vlan_presence" USING btree ("trunk_set");
CREATE INDEX "trunkset_vlan_presence_vlan_idx" ON "trunkset_vlan_presence" USING btree ("vlan");
CREATE INDEX "vlan_subnet_presence_subnet_idx" ON "vlan_subnet_presence" USING btree ("subnet");
CREATE INDEX "vlan_subnet_presence_vlan_idx" ON "vlan_subnet_presence" USING btree ("vlan");
